# Generated by Django 3.2.3 on 2021-05-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210529_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttradie',
            old_name='tradie_name',
            new_name='tradie_id',
        ),
    ]
