# Generated by Django 3.2.3 on 2021-05-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_tradie_name_projecttradie_tradie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Building', 'Building'), ('Complate', 'Complate'), ('Planned', 'Planned')], default='Planned', max_length=50, null=True),
        ),
    ]
